### ISSUE TITLE
BwD的新机制

### ISSUE THREAD

**Issue by UPDAT-E** [zaixia108/WTautoFull#23]
来自12月20日的新更新 Bwd更改了海战的机制：如果玩家不自己使用主炮命中一次的话 收益就不会被结算 剩下的只有亏损的维修费 
这使得以往的脚本都不再起作用 请问这在目前是否有解决方法 或是否代表着海战挂机彻底消失

**Comment by Zeppelin5079** [comment]
目前大概只能手動中一發吧，看如果之後海戰越來越少人玩，能不能逼bwd改回去

**Comment by zaixia108** [comment]
并不代表彻底消失，解决方案有几种，但是这基本代表着免费方案消失

**Comment by Black-Woof** [comment]
如何看待？
![152105da81cb39dba8e30e9295160924aa18303c](https://user-images.githubusercontent.com/39839039/209357948-6b37ed21-2265-429b-95ad-0fe2a53c62fe.jpg)

**Comment by UPDAT-E** [comment]
只能说希望新的本地计算脚本还能开发出来 因为这样即使因为开发成本大是付费制度也有可能做到买断制 我已经在TB平台上看到了关于服务器计算脚本已经有解决方案正在开发的消息 但是服务器计算就代表着会不断产生商家成本 就需要用户埋单 据我看到的价格约为每月60r左右 如果持续挂机的话还是蛮值得的 不过似乎尚未实际应用 本人（出于某些个人偏好与实际的原因）也更偏向于买断制的本地计算（虽然希望渺茫 且基本可以确定bwd会更进一步削弱海战的收益及改变机制使脚本更加难以实现）
- [ ] 对于对脚本玩家的攻击 我见过许多理由 破坏游戏环境等都不少 我也无法反驳 但bwd对脚本的直接砍杀并不能以此为理由 如果一个游戏的肝度正常 我想正常人也不会开脚本 但是现在的收益甚至完全不足以支撑新玩家足够的心理动力去肝 作为一个入坑不到一年的新人 我并没有机会亲自经历曾经收益正常的时期 但是每个人都可以真切的体会到现状 不过也许正如某帖子所说 像我这种会使用脚本的人 本身就有问题。
bwd是个好的策划 但他不是一个好的策划
市场没有竞品和玩家巨大的沉没成本让他用自己的“才华”为公司挣到了足够的钱 他没有被换掉就证明了一切 作为一个策划 以钱为目的并没有错误 但是作为一个策划 他通过直接降低肥氪金玩家的游戏体验的方法挣钱 就使他失去了木琴
话题扯到策划身上并非为脚本辩解之便利 即使海战脚本真的彻底消失 又有多少原来的脚本玩家可以做到彻底从战雷消失呢 市场上的竞品也许有 DCS至少算一个 也许以前的定位差距还甚大 但现在bwd对顶级礼包机的定价已经逼近DCS中飞机不打折的价格了 更不用说DCS的DLC价格是处于常年打折状态的
但是战雷不仅有飞机 它还有坦克 有海战 
且战雷是一个“竞技”游戏
竞技性也许是海战脚本被厌恶的理由之一 在任何竞技游戏中 脚本队友甚至脚本敌人都是对真人玩家体验的削弱 但是战雷除了竞技性 还有科技树的设定 在这个设定下 对局便不只是“重在参与” 而是为了一个目的 在“搬炸弹” “海战挂机”等设定下 “开线”与“竞技”严重脱节 “空格猴子”和“海战挂机”因为其方法等问题与主要目的为“战斗”的玩家产生的矛盾便出现了。但是希望明白“bwd砍脚本不是为了玩家的游戏体验”
而“海战挂机”被砍掉 代表着bwd吃掉了一个玩家免费方便获取银币的途径 而这个途径在某些方面与重点在对局的玩家是不谋而合的
最后 结尾很匆忙 似乎内容也有很多逻辑性错误 前文说不是为挂机辩解 后文似乎又完全是在辩解 不过 只能说 希望海战挂机不会消失 尽管我发现后面有些话完全悖逆自己的观点 这种话要是在辩论上出现估计会挨大嘴巴子
最后的最后 我来给自己叠甲-
我只是希望战雷的本地计算海战脚本可以恢复 如果令任何人感到不适 权当中间这段话是我一时起意写出来又不想删去的累赘 我也不想参与任何脚本使用者和正常玩家的争论 只是一个因为陆战见光死钱要亏没希望海战挂机回来的战雷新手玩家 谢谢

**Comment by UPDAT-E** [comment]
> 如何看待？
> 
> ![152105da81cb39dba8e30e9295160924aa18303c](https://user-images.githubusercontent.com/39839039/209357948-6b37ed21-2265-429b-95ad-0fe2a53c62fe.jpg)
> 
> 

希望能出

**Comment by Zeppelin5079** [comment]
> 并不代表彻底消失，解决方案有几种，但是这基本代表着免费方案消失

沒關係，寧願給你錢也不要搞BWD一毛

**Comment by UPDAT-E** [comment]
> 并不代表彻底消失，解决方案有几种，但是这基本代表着免费方案消失

请问作者会制作新的脚本吗

**Comment by zaixia108** [comment]
已经制作完新的脚本，文件分享在QQ频道：
战争雷霆银狮救济中心

**Comment by UPDAT-E** [comment]
> 已经制作完新的脚本，文件分享在QQ频道：
> 战争雷霆银狮救济中心

**Comment by Halcyon9453** [comment]
不確定你們能不能用 Discord, 不過可以考慮開一個 Discord頻道專門推送更新資訊及腳本下載等等，還蠻方便管理的
